#!/usr/bin/env node
// scripts/build.js
// Reads data/packets/*.json + data/registry.json → generates js/packet-data.js
//
// Usage:
//   node scripts/build.js          # regenerate from individual JSONs
//   node scripts/build.js --init   # first time: extract from main.js → JSONs → packet-data.js
'use strict';

const fs = require('fs');
const path = require('path');

const BASE = path.join(__dirname, '..');
const DATA = path.join(BASE, 'data');
const PACKETS_DIR = path.join(DATA, 'packets');
const JS_DIR = path.join(BASE, 'js');
const MAIN_JS = path.join(JS_DIR, 'main.js');
const REGISTRY = path.join(DATA, 'registry.json');
const OUT = path.join(JS_DIR, 'packet-data.js');

function main() {
  const arg = process.argv[2];

  if (arg === '--init') {
    initFromMainJs();
    return;
  }

  buildFromJsons();
}

// --init: one-time extraction from main.js
function initFromMainJs() {
  const mainJs = fs.readFileSync(MAIN_JS, 'utf8');
  const packets = parsePacketsFromJs(mainJs);
  console.log(`Extracted ${packets.length} packets from main.js`);

  fs.mkdirSync(PACKETS_DIR, { recursive: true });

  // Write individual JSONs
  const registry = [];
  for (const p of packets) {
    const fname = p.id + '.json';
    fs.writeFileSync(path.join(PACKETS_DIR, fname), JSON.stringify(p, null, 2));
    registry.push({
      id: p.id, hex: p.hex, dec: p.dec, dir: p.dir,
      state: p.state, name: p.name, desc: p.desc,
      tags: p.tags || [], file: fname
    });
  }
  fs.writeFileSync(REGISTRY, JSON.stringify(registry, null, 2));
  console.log(`Wrote ${packets.length} JSONs → data/packets/`);
  console.log(`Wrote data/registry.json`);

  // Also build the JS output
  writePacketDataJs(packets);
}

// Default: rebuild from data/packets/*.json
function buildFromJsons() {
  const files = fs.readdirSync(PACKETS_DIR).filter(f => f.endsWith('.json'));
  const packets = [];

  for (const f of files) {
    const raw = fs.readFileSync(path.join(PACKETS_DIR, f), 'utf8');
    packets.push(JSON.parse(raw));
  }

  // Sort by state order, then by hex ID
  const stateOrder = { HANDSHAKING: 0, LOGIN: 1, STATUS: 2, PLAY: 3 };
  packets.sort((a, b) => {
    if (a.state !== b.state) return stateOrder[a.state] - stateOrder[b.state];
    if (a.dir !== b.dir) return a.dir === 'SERVERBOUND' ? -1 : 1;
    return a.dec - b.dec;
  });

  console.log(`Loaded ${packets.length} packets from data/packets/`);

  // Regenerate registry
  const registry = packets.map(p => ({
    id: p.id, hex: p.hex, dec: p.dec, dir: p.dir,
    state: p.state, name: p.name, desc: p.desc,
    tags: p.tags || [], file: p.id + '.json'
  }));
  fs.writeFileSync(REGISTRY, JSON.stringify(registry, null, 2));
  console.log(`Regenerated data/registry.json`);

  writePacketDataJs(packets);
}

function writePacketDataJs(packets) {
  const json = JSON.stringify(packets);
  const out = [
    '// AUTO-GENERATED by scripts/build.js — DO NOT EDIT',
    '// Source: data/packets/*.json',
    '// Run `node scripts/build.js` to regenerate',
    '',
    'const PACKETS = ' + json + ';',
    ''
  ].join('\n');
  fs.writeFileSync(OUT, out);
  console.log(`Generated js/packet-data.js (${Buffer.byteLength(out, 'utf8')} bytes, ${packets.length} packets)`);
}

function parsePacketsFromJs(src) {
  const start = src.indexOf('const PACKETS = [');
  if (start === -1) throw new Error('PACKETS array not found in main.js — already migrated?');

  let depth = 0;
  let i = start + 'const PACKETS = ['.length - 1;
  for (; i < src.length; i++) {
    if (src[i] === '[') depth++;
    else if (src[i] === ']') { depth--; if (depth === 0) break; }
  }
  const arraySrc = src.substring(start + 'const PACKETS ='.length, i + 1);
  return eval(arraySrc);
}

main();
